general:
  dataset:
    name: CIFAR10
    resolution: 32
    path: data
    noaugment: True
  model:
    name: ResNet34
    num_classes: 10
  repeats: 2
  repeats_start: 1
  results_path: results
  epochs: 50
  batch_size: 128
  num_workers: 2
  gcp: True
  tpu: True
  bucket_path: gs://autoopt
experiments:
  - optimizer:
      name: Adagrad
      lr: 0.01
  - optimizer:
      name: Adagrad
      lr: 0.001
  - optimizer:
      name: Adagrad
      lr: 0.0001
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.1
      inner_optimizer:
        name: Adagrad
        lr: 1
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.5
      inner_optimizer:
        name: Adagrad
        lr: 1