general:
  dataset:
    name: CIFAR10
    resolution: 32
    path: data
    noaugment: True
  model:
    name: ResNet34
    num_classes: 10
  repeats: 3
  results_path: results
  epochs: 50
  batch_size: 16
  num_workers: 4
  gcp: True
  tpu: True
  bucket_path: gs://kamil-piechowiak-weights-transfer/autoopt
experiments:
  - optimizer:
      name: Adam
      lr: 0.005
  - optimizer:
      name: Adam
      lr: 0.002
  - optimizer:
      name: Adam
      lr: 0.0005
  - optimizer:
      name: Adam
      lr: 0.0001