general:
  dataset:
    name: CIFAR10
    resolution: 32
    path: data
    noaugment: True
  model:
    name: ResNet34
    num_classes: 10
  repeats: 2
  repeats_start: 1
  results_path: results
  epochs: 100
  batch_size: 16
  num_workers: 4
  gcp: True
  tpu: True
  bucket_path: gs://kamil-piechowiak-weights-transfer/autoopt
experiments:
  - optimizer:
      name: SGD
      lr: 1
  - optimizer:
      name: Adam
      lr: 0.001
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.1
      inner_optimizer:
        name: SGD
        lr: 1
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.1
      inner_optimizer:
        name: Adam
        lr: 1
  - optimizer:
      name: SGD
      lr: 0.1
  - optimizer:
      name: Adam
      lr: 0.01
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: keep
      search_strategy: goldstein
      batch_strategy: single
      c: 0.1
      inner_optimizer:
        name: SGD
        lr: 1
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.5
      inner_optimizer:
        name: Adam
        lr: 1