general:
  epochs: 10
  problem: quadratic_deep
experiments:
  - optimizer:
      name: ArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.5
      inner_optimizer:
        name: Adam
        lr: 1
  - optimizer:
      name: ArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.5
      inner_optimizer:
        name: Adam
        lr: 1
      weight_decay: 0.1