general:
  dataset:
    name: FASHION_MNIST
    resolution: 28
    path: data
    noaugment: False
    test: True
  task: vae
  model:
    name: VAE
  repeats: 1
  repeats_start: 0
  results_path: results
  epochs: 50
  batch_size: 64
  num_workers: 2
  gcp: True
  tpu: False
  bucket_path: gs://autoopt
experiments:
  - optimizer:
      name: Adam
      lr: 0.00001
    repeats: 3
    repeats_start: 0
  - optimizer:
      name: ArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.5
      normalize: normalize
      inner_optimizer:
        name: Adam
        lr: 1
  - optimizer:
      name: ArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.5
      normalize: normalize
      inner_optimizer:
        name: Adam
        lr: 1
      weight_decay: 0.01
  - optimizer:
      name: Adagrad
      lr: 0.0001
  - optimizer:
      name: Adagrad
      lr: 0.001
  - optimizer:
      name: SGD
      lr: 0.001
  - optimizer:
      name: SGD
      lr: 0.0001
  - optimizer:
      name: SGD
      lr: 0.00001