general:
  dataset:
    name: FASHION_MNIST
    resolution: 28
    path: data
    noaugment: False
    test: True
  task: vae
  model:
    name: VAE
  repeats: 1
  repeats_start: 0
  results_path: results
  epochs: 50
  batch_size: 64
  num_workers: 2
  gcp: True
  tpu: False
  bucket_path: gs://autoopt
experiments:
  - optimizer:
      name: Adam
      lr: 0.0001
    repeats: 2
    repeats_start: 1
  - optimizer:
      name: Adam
      lr: 0.001
    repeats: 2
    repeats_start: 1
  - optimizer:
      name: Adam
      lr: 0.01
    repeats: 2
    repeats_start: 1
  - optimizer:
      name: Adam
      lr: 0.0001
    scheduler:
      name: OneCycleLR
      max_lr: 0.001
      total_steps: 50
      three_phase: 1
    repeats: 3
    repeats_start: 0
  - optimizer:
      name: Adam
      lr: 0.001
    scheduler:
      name: OneCycleLR
      max_lr: 0.01
      total_steps: 50
      three_phase: 1
    repeats: 2
    repeats_start: 1
  - optimizer:
      name: ArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.5
      inner_optimizer:
        name: Adam
        lr: 1
    repeats: 2
    repeats_start: 1
  - optimizer:
      name: ArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.5
      inner_optimizer:
        name: Adam
        lr: 1
      weight_decay: 0.01
    repeats: 2
    repeats_start: 1
  - optimizer:
      name: ArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.5
      normalize: normalize
      inner_optimizer:
        name: Adam
        lr: 1
    repeats: 2
    repeats_start: 1
  - optimizer:
      name: ArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.5
      normalize: normalize
      inner_optimizer:
        name: Adam
        lr: 1
      weight_decay: 0.01
    repeats: 2
    repeats_start: 1
  - optimizer:
      name: Adagrad
      lr: 0.001
  - optimizer:
      name: Adagrad
      lr: 0.01
  - optimizer:
      name: Adagrad
      lr: 0.1
  - optimizer:
      name: Adagrad
      lr: 0.01
    scheduler:
      name: OneCycleLR
      max_lr: 0.1
      total_steps: 50
      three_phase: 1
      cycle_momentum: False
  - optimizer:
      name: ArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.1
      inner_optimizer:
        name: Adagrad
        lr: 1
  - optimizer:
      name: ArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.1
      inner_optimizer:
        name: Adagrad
        lr: 1
      weight_decay: 0.01
  - optimizer:
      name: ArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.1
      normalize: normalize
      inner_optimizer:
        name: Adagrad
        lr: 1
  - optimizer:
      name: ArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.1
      normalize: normalize
      inner_optimizer:
        name: Adagrad
        lr: 1
      weight_decay: 0.01
  - optimizer:
      name: SGD
      lr: 0.01
  - optimizer:
      name: SGD
      lr: 0.1
  - optimizer:
      name: SGD
      lr: 1
  - optimizer:
      name: SGD
      lr: 0.1
    scheduler:
      name: OneCycleLR
      max_lr: 1
      total_steps: 50
      three_phase: 1
      cycle_momentum: False
  - optimizer:
      name: ArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.1
      inner_optimizer:
        name: SGD
        lr: 1
  - optimizer:
      name: ArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.1
      inner_optimizer:
        name: SGD
        lr: 1
      weight_decay: 0.01
  - optimizer:
      name: ArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.1
      normalize: normalize
      inner_optimizer:
        name: SGD
        lr: 1
  - optimizer:
      name: ArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.1
      normalize: normalize
      inner_optimizer:
        name: SGD
        lr: 1
      weight_decay: 0.01
  - optimizer:
      name: PalOptimizer
    dataset:
      name: CIFAR100
      resolution: 32
      path: data
      noaugment: False
      test: True
    model:
      name: ResNet34
      num_classes: 100
    epochs: 150
    task: classification