general:
  dataset:
    name: FASHION_MNIST
    resolution: 28
    path: data
    noaugment: True
  model:
    name: SmallResnet20
    num_classes: 10
  repeats: 3
  repeats_start: 0
  results_path: results
  epochs: 50
  batch_size: 128
  num_workers: 2
  gcp: True
  tpu: False
  bucket_path: gs://autoopt
experiments:
  - optimizer:
      name: ArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.5
      inner_optimizer:
        name: Adam
        lr: 1
      normalize: normalize
  - optimizer:
      name: ArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.5
      inner_optimizer:
        name: Adam
        lr: 1
      weight_decay: 0.1
      normalize: normalize
  - optimizer:
      name: ArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.1
      inner_optimizer:
        name: Adagrad
        lr: 1
      normalize: normalize
  - optimizer:
      name: ArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.1
      inner_optimizer:
        name: Adagrad
        lr: 1
      weight_decay: 0.1
      normalize: normalize
  - optimizer:
      name: ArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.1
      inner_optimizer:
        name: SGD
        lr: 1
      normalize: normalize
  - optimizer:
      name: ArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.1
      inner_optimizer:
        name: SGD
        lr: 1
      weight_decay: 0.1
      normalize: normalize