general:
  dataset:
    name: CIFAR10
    resolution: 32
    path: data
    noaugment: True
  model:
    name: SmallResnet20
    num_classes: 10
  repeats: 1
  results_path: tmp
  epochs: 2
  batch_size: 32
  num_workers: 2
  gcp: False
  tpu: False
  stats:
    gradient_direction:
      batch_sizes: [16]
      num_workers: 2
experiments:
  - optimizer:
      name: Adam
      lr: 0.001
    append_to_name: grad