general:
  dataset:
    name: CIFAR10
    resolution: 224
    path: data
    noaugment: True
  model:
    name: tf_efficientnet_b0
    num_classes: 10
  repeats: 1
  results_path: results
  epochs: 20
  batch_size: 16
  num_workers: 4
  gcp: True
  tpu: True
  bucket_path: gs://kamil-piechowiak-weights-transfer/autoopt
  stats:
    gradient_direction:
      batch_sizes: [8, 16]
      num_workers: 4
experiments:
  - optimizer:
      name: Adam
      lr: 0.001
    append_to_name: grad2