general:
  dataset:
    name: CIFAR10
    resolution: 224
    path: data
  model:
    name: tf_efficientnet_b0
    num_classes: 10
  repeats: 3
  results_path: results
  epochs: 100
  batch_size: 16
  num_workers: 4
  gcp: True
  tpu: True
  bucket_path: gs://kamil-piechowiak-weights-transfer/autoopt
experiments:
  - optimizer:
      name: SGD
      lr: 0.1
  - optimizer:
      name: SGD
      lr: 0.01
  - optimizer:
      name: SGD
      lr: 0.001
  - optimizer:
      name: SGD
      lr: 0.0001
  - optimizer:
      name: Adam
      lr: 0.1
  - optimizer:
      name: Adam
      lr: 0.01
  - optimizer:
      name: Adam
      lr: 0.001
  - optimizer:
      name: Adam
      lr: 0.0001
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: max
      search_strategy: armijo
      batch_strategy: single
      inner_optimizer:
        name: SGD
        lr: 1
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: max
      search_strategy: armijo
      batch_strategy: double
      inner_optimizer:
        name: SGD
        lr: 1
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: keep
      search_strategy: armijo
      batch_strategy: single
      inner_optimizer:
        name: SGD
        lr: 1
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.01
      inner_optimizer:
        name: SGD
        lr: 1
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      inner_optimizer:
        name: SGD
        lr: 1
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.0003
      inner_optimizer:
        name: SGD
        lr: 1
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: increase
      c: 0.01
      gamma: 2.0
      search_strategy: armijo
      batch_strategy: single
      inner_optimizer:
        name: SGD
        lr: 1
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: increase
      c: 0.01
      gamma: 2.0
      search_strategy: armijo
      batch_strategy: double
      inner_optimizer:
        name: SGD
        lr: 1
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: keep
      search_strategy: goldstein
      batch_strategy: single
      inner_optimizer:
        name: SGD
        lr: 1
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: keep
      search_strategy: goldstein
      batch_strategy: double
      inner_optimizer:
        name: SGD
        lr: 1
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: keep
      search_strategy: goldstein
      batch_strategy: single
      inner_optimizer:
        name: Adam
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: keep
      search_strategy: goldstein
      batch_strategy: double
      inner_optimizer:
        name: Adam
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.01
      inner_optimizer:
        name: Adam
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: double
      gamma: 1.01
      inner_optimizer:
        name: Adam
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: keep
      search_strategy: goldstein
      batch_strategy: single
      inner_optimizer:
        name: Adagrad
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: keep
      search_strategy: goldstein
      batch_strategy: double
      mizer:
        name: Adagrad
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.01
      inner_optimizer:
        name: Adagrad
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: double
      gamma: 1.01
      inner_optimizer:
        name: Adagrad
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.01
      c: 0.1
      inner_optimizer:
        name: SGD
        lr: 1
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.01
      c: 0.05
      inner_optimizer:
        name: SGD
        lr: 1
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.01
      c: 0.01
      inner_optimizer:
        name: SGD
        lr: 1
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: keep
      search_strategy: goldstein
      batch_strategy: single
      c: 0.1
      inner_optimizer:
        name: SGD
        lr: 1
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: keep
      search_strategy: goldstein
      batch_strategy: single
      c: 0.05
      inner_optimizer:
        name: SGD
        lr: 1
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: keep
      search_strategy: goldstein
      batch_strategy: single
      c: 0.01
      inner_optimizer:
        name: SGD
        lr: 1
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.1
      inner_optimizer:
        name: Adam