general:
  dataset:
    name: CIFAR10
    resolution: 224
    path: data
  model:
    name: tf_efficientnet_b0
    num_classes: 10
  repeats: 1
  results_path: results
  epochs: 50
  batch_size: 16
  num_workers: 4
  gcp: True
  tpu: True
  bucket_path: gs://kamil-piechowiak-weights-transfer/autoopt
experiments:
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: keep
      search_strategy: goldstein
      batch_strategy: single
      c: 0.1
      goldstein_c: 0.8
      inner_optimizer:
        name: SGD
        lr: 1
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: keep
      search_strategy: goldstein
      batch_strategy: single
      c: 0.2
      inner_optimizer:
        name: SGD
        lr: 1
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.1
      inner_optimizer:
        name: Adam
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.2
      inner_optimizer:
        name: Adam
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.5
      inner_optimizer:
        name: Adam
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.01
      inner_optimizer:
        name: Adam
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: keep
      search_strategy: goldstein
      batch_strategy: single
      c: 0.1
      goldstein_c: 0.5
      inner_optimizer:
        name: SGD
        lr: 1
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: keep
      search_strategy: goldstein
      batch_strategy: single
      c: 0.05
      goldstein_c: 0.5
      inner_optimizer:
        name: SGD
        lr: 1
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: keep
      search_strategy: goldstein
      batch_strategy: single
      c: 0.01
      goldstein_c: 0.5
      inner_optimizer:
        name: SGD
        lr: 1
      name: DistributedArmijoLineSearch
      reset_strategy: max
      search_strategy: armijo
      batch_strategy: single
      inner_optimizer:
        name: SGD
        lr: 1
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: max
      search_strategy: armijo
      batch_strategy: double
      inner_optimizer:
        name: SGD
        lr: 1
  - optimizer:
      name: DistributedArmijoLineSearch
      reset_strategy: keep
      search_strategy: armijo
      batch_strategy: single
      inner_optimizer:
        name: SGD
        lr: 1