general:
  dataset:
    name: FASHION_MNIST
    resolution: 28
    path: data
    noaugment: False
    test: True
  model:
    name: SmallResnet20
    num_classes: 10
  repeats: 1
  repeats_start: 0
  results_path: tmp
  epochs: 10
  batch_size: 16
  num_workers: 1
  gcp: False
  tpu: False
experiments:
  - optimizer:
      name: PalOptimizer
  - optimizer:
      name: ArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.5
      inner_optimizer:
        name: Adam
        lr: 1
      weight_decay: 0.01