general:
  dataset:
    name: CIFAR10
    resolution: 32
    path: data
    noaugment: False
    test: True
  model:
    name: SmallResnet20
    num_classes: 10
  repeats: 1
  repeats_start: 0
  results_path: tmp
  epochs: 10
  batch_size: 16
  num_workers: 1
  gcp: False
  tpu: False
experiments:
  - optimizer:
      name: PalOptimizer