general:
  dataset:
    name: CIFAR10
    resolution: 224
    path: data
  model:
    name: tf_efficientnet_b0
    num_classes: 10
  repeats: 1
  results_path: results
  epochs: 10
  batch_size: 16
  num_workers: 4
  gcp: True
  tpu: True
  bucket_path: gs://kamil-piechowiak-weights-transfer/autoopt
experiments:
  - optimizer:
      name: ArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      inner_optimizer:
        name: SGD
        lr: 1