general:
  dataset:
    name: CIFAR10
    resolution: 32
    path: data
    noaugment: False
  model:
    name: ResNet34
    num_classes: 10
  repeats: 1
  repeats_start: 0
  results_path: results
  epochs: 50
  batch_size: 128
  num_workers: 2
  gcp: True
  tpu: False
  bucket_path: gs://autoopt
experiments:
  - optimizer:
      name: ArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.5
      lr_multiplier: 8.8
      inner_optimizer:
        name: Adam
        lr: 1
  - optimizer:
      name: ArmijoLineSearch
      reset_strategy: increase
      search_strategy: armijo
      batch_strategy: single
      gamma: 1.001
      c: 0.1
      report_critical_profiles: True
      random_profile_prob: 0.01
      inner_optimizer:
        name: Adagrad
        lr: 1
    append_to_name: critical_prof
  - optimizer:
      name: Adam
      lr: 0.01
    scheduler:
      name: OneCycleLR
      max_lr: 0.1
      total_steps: 50
      three_phase: 1
      repeats: 3
  - optimizer:
      name: Adagrad
      lr: 0.1
    scheduler:
      name: OneCycleLR
      max_lr: 1
      total_steps: 50
      three_phase: 1
  - optimizer:
      name: SGD
      lr: 1
    scheduler:
      name: OneCycleLR
      max_lr: 10
      total_steps: 50
      three_phase: 1