general:
  dataset:
    name: CIFAR10
    resolution: 224
    path: data
    noaugment: True
  model:
    name: tf_efficientnet_b0
    num_classes: 10
  repeats: 1
  results_path: results
  epochs: 20
  batch_size: 16
  num_workers: 8
  gcp: True
  tpu: True
  bucket_path: gs://kamil-piechowiak-weights-transfer/autoopt
  stats:
    profile:
      batch_sizes: [4, 8, 16, 32]
      num_workers: 8
experiments:
  - optimizer:
      name: OptimizerWrapper
      inner_optimizer:
        name: Adam
        lr: 0.001
    append_to_name: prof